server:
  port: 8087

spring:
  application:
    name: API-GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: BOOKING-SERVICE
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/v1/bookings/**

        - id: CINEMA-HALL-SERVICE
          uri: lb://CINEMA-HALL-SERVICE
          predicates:
            - Path=/api/v1/cinema_hall/**

        - id: MOVIES-SERVICE
          uri: lb://MOVIES-SERVICE
          predicates:
            - Path=/api/v1/movies/**

        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**

        - id: SHOWTIME-SERVICE
          uri: lb://SHOWTIME-SERVICE
          predicates:
            - Path=/api/v1/showtimes/**

        - id: TICKET-SERVICE
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/api/v1/tickets/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka