server:
  port: 8089

spring:
  application:
    name: API-GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter

        - id: TICKET-SERVICE
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/api/V1/tickets/**
          filters:
            - AuthenticationFilter

        - id: SHOWTIME-SERVICE
          uri: lb://SHOWTIME-SERVICE
          predicates:
            - Path=/api/v1/showtimes/**
          filters:
            - AuthenticationFilter

        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - AuthenticationFilter

        - id: MOVIE-SERVICE
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/api/v1/movies/**
          filters:
            - AuthenticationFilter

        - id: FOOD-SERVICE
          uri: lb://FOOD-SERVICE
          predicates:
            - Path=/api/v1/foods/**
          filters:
            - AuthenticationFilter

        - id: CINEMAHALL-SERVICE
          uri: lb://CINEMAHALL-SERVICE
          predicates:
            - Path=/api/v1/cinema-halls/**
          filters:
            - AuthenticationFilter

        - id: BOOKING-SERVICE
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/v1/bookings/**
          filters:
            - AuthenticationFilter



# Eureka server config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
